### ISSUE TITLE
Collect mail address and password encoding in base 64

### ISSUE THREAD

**Issue by LilyaMel** [GaelleMarais/Virtual-Assistant#5]

**Comment by GaelleMarais** [comment]
I would like you to store these infos in the file `config_email` with : 
-1st line : email adress (transparent)
-2nd line: email adress+password (encoded)

So the file should looks like that : 

```
mangabountynaia@gmail.com
AG1hbmdhYm91bnR5bmFpYUBnbWFpbC5jb20ATUFOR0FCT1VOVFlOQUlB
```
